Factory/Models/Engineer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }
    [Required(ErrorMessage = "What is this engineer's name?")]
    public string Name { get; set; }
    [Required(ErrorMessage = "What are this engineer's details?")]
    public string Details { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public Machine Machine { get; set; }
    public int MachineId { get; set; }
    public Engineer Engineer { get; set; }
    public int EngineerId { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachines { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    [Required(ErrorMessage = "What type of machine is this?")]
    public string Type { get; set; }
    [Required(ErrorMessage = "What are this machine's details?")]
    public string Details { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
      else
      {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Type");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
#nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    private readonly FactoryContext _db;

    public HomeController(FactoryContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      Engineer[] engineers = _db.Engineers.ToArray();
      Machine[] machines = _db.Machines.ToArray();
      Dictionary<string, object[]> model = new Dictionary<string, object[]>();
      model.Add("engineers", engineers);
      model.Add("machines", machines);
      return View(model);
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
#nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Certify a New Machine for @Model.Name</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")<br /><br />

  <input type="submit" value="Save" />
}

<div class="navlinks">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a New Engineer</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

<div class="form">
  @using (Html.BeginForm())
  {
    <div class="form-block">
      @Html.LabelFor(model => model.Name)
      @Html.TextBoxFor(model => model.Name)
    </div>
    <div class="form-block">
      @Html.LabelFor(model => model.Details)
      @Html.TextAreaFor(model => model.Details, new { @class = "textbox" })
    </div>
    <div class="form-block">
      <input type="submit" value="Add Engineer" />
    </div>
  }
</div>

<div class="navlinks">
  <p>@Html.ActionLink("Show all Engineers", "Index")</p>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete @Model.Name?</h2>
<h4 class="light-text">You cannot undo this.</h4><br />

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<div class="navlinks">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>About @Model.Name: <span class="light-text">Engineer</span></h2>
<p class="description">@Html.DisplayFor(model => model.Details)</p>

@if (@Model.JoinEntities.Count == 0)
{
  <p>@Model.Name is not licensed to repair any machines yet.</p>
}
else
{
  <h4>@Model.Name is licensed to repair the following machines:</h4>
  <ul>
  @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li class="lists">@join.Machine.Type
        @using (Html.BeginForm("DeleteJoin", "Engineers"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" />
        }
      </li>
    }
  </ul>
}

<div class="navlinks four-links">
  <p>@Html.ActionLink("Back to list", "Index")</p>
  <p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Add Machine for Engineer", "AddMachine", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit @Model.Name's Profile</h2><br />

<div class="form">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)

    <div class="form-block">
      @Html.LabelFor(model => model.Name)
      @Html.EditorFor(model => model.Name)
    </div>
    <div class="form-block">
      @Html.LabelFor(model => model.Details)
      @Html.TextAreaFor(model => model.Details, new { @class = "textbox" })
    </div>
    <div class="form-block">
      <input type="submit" value="Save" />
    </div>
  }
</div>

<div class="navlinks">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h2>Engineers</h2>

@if (@Model.Count == 0)
{
  <h3>No engineers have been added yet!</h3>
}
else
{
  <ul>
  @foreach (Engineer engineer in Model)
    {
      <li class="lists">@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
    }
  </ul>
}

<div class="navlinks two-links">
  <p>@Html.ActionLink("Add New Engineer", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h2>Engineer and Machine Directory</h2>

<div class="splash-container">
  @using (Html.BeginForm("Index", "Engineers", FormMethod.Get)) //make sure the form triggers a get request
  {
    <button type="submit" class="navlinks-home">@Html.ActionLink("Engineers", "Index", "Engineers")</button>
  }
  <hr />

  @if (Model["engineers"].Length == 0)
  {
    <p>No engineers have been added yet.</p>
  }
  <ul>
    @foreach (Engineer engineer in Model["engineers"])
    {
      <li class="lists">@Html.ActionLink(@engineer.Name, "Details", "Engineers", new { id = @engineer.EngineerId })</li>
    }
  </ul>
</div>

<div class="splash-container">
  @using (Html.BeginForm("Index", "Machines", FormMethod.Get)) //make sure the form triggers a get request
  {
    <button type="submit" class="navlinks-home">@Html.ActionLink("Machines", "Index", "Machines")</button>
  }
  <hr />
  @if (Model["machines"].Length == 0)
  {
    <p>No machines have been added yet.</p>
  }
  <ul>
    @foreach (Machine machine in Model["machines"])
    {
      <li class="lists">@Html.ActionLink(@machine.Type, "Details", "Machines", new { id = @machine.MachineId })</li>
    }
  </ul>
</div>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Certify a New Engineer for @Model.Type</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")<br /><br />

  <input type="submit" value="Save" />
}

<div class="navlinks">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a New Machine</h2>

<p>@Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

<div class="form">
  @using (Html.BeginForm())
  {
    <div class="form-block">
      @Html.LabelFor(model => model.Type)
      @Html.TextBoxFor(model => model.Type)
    </div>
    <div class="form-block">
      @Html.LabelFor(model => model.Details)
      @Html.TextAreaFor(model => model.Details, new { @class = "textbox" })
    </div>
    <div class="form-block">
      <input type="submit" value="Add Machine" />
    </div>
  }
</div>

<div class="navlinks">
  <p>@Html.ActionLink("Show all Machines", "Index")</p>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete @Model.Type?</h2>
<h4 class="light-text">You cannot undo this.</h4><br />

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<div class="navlinks">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>@Model.Type Details: <span class="light-text">Machine</span></h2>
<p class="description">@Html.DisplayFor(model => model.Details)</p>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine is not licensed to be repaired by any engineers</p>
}
else
{
  <h4>This machine is licensed to be repaired by:</h4>
  <ul>
  @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li class="lists">@join.Engineer.Name
        @using (Html.BeginForm("DeleteJoin", "Machines"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" />
        }
      </li>
    }
  </ul>
}

<div class="navlinks four-links">
  <p>@Html.ActionLink("Back to list", "Index")</p>
  <p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Add Engineer to Machine", "AddEngineer", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit Details for @Model.Type</h2><br />

<div class="form">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    <div class="form-block">
      @Html.LabelFor(model => model.Type)
      @Html.EditorFor(model => model.Type)
    </div>
    <div class="form-block">
      @Html.LabelFor(model => model.Details)
      @Html.TextAreaFor(model => model.Details, new { @class = "textbox" })
    </div>
    <div class="form-block">
      <input type="submit" value="Save" />
    </div>
  }
</div>

<div class="navlinks">
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h2>Machines</h2>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
}
else
{
  <ul>
  @foreach (Machine machine in Model)
    {
      <li class="lists">@Html.ActionLink($"{machine.Type}", "Details", new { id = machine.MachineId })</li>
    }
  </ul>
}

<div class="navlinks two-links">
  <p>@Html.ActionLink("Add New Machine", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Factory/Views/Shared/Footer.cshtml
<div id="footer"><a href='/'>Dr. Sillystringz's Engineering Co. Established in 1990</a></div>

Factory/Views/Shared/Header.cshtml
<nav class="navbar">
  <a class="navbar-brand" href="/">
    <h1> Dr. Sillystringz's Engineering Co. </h1>
  </a>
  @Html.ActionLink("Home", "Index", "Home")
  @Html.ActionLink("Back to list", "Index", "Engineers")
</nav>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Factory</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
  @await Html.PartialAsync("Header")
  <div class="container">
    @RenderBody()
  </div>
  @await Html.PartialAsync("Footer")
</body>

</html>